FROM node:20.18 AS build-env
ARG APP_TAG_VERSION

ENV APP_VERSION=${APP_TAG_VERSION}

RUN echo "Testing APP_VERSION: $APP_VERSION" && \
  node -e "console.log('(API) => process.env.APP_VERSION:', process.env.APP_VERSION);"
